name: Go analysis
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'

env:
  DB_URL: '${{ secrets.TEST_DB_URL }}'
  API_KEY: '${{ secrets.TEST_API_KEY }}'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Install tools
        run: |
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/mgechev/revive@latest

      - name: Go vet
        run: go vet .

      - name: Run static check
        run: staticcheck ./...

      - name: Run revive linter
        run: revive -config lint-config.toml -formatter friendly ./...

      - name: Go test
        run: go test ./...
